### PR TITLE
GVN-329 add explorer links to all success modals

### PR DESCRIPTION
**Pull request by GHesericsu**

### CODE REVIEW

**Review by Tristyn — COMMENTED** [review]
This is some spaghetti code

I see why you're passing down `getTxExplorerUrl` from a component through 3 functions because it has settings that come from a context.

I see 2 alternatives
1) Return the txid to the component and send notifications there.
2) Refactor txs to be a hook that returns a send function.

In 1 and 2 the component or hook has access to `getTxExplorerUrl` via context api

The current version is certainly really complex

**Comment by GHesericsu** [comment]
@Tristyn haha that's what I thought. I didn't want to do it this way either. Was trying to not change too much structure. I should return [res, txid] after we send transactions like we did on v1. I think I know what to do on either 1 or 2. Was gonna use steps.success to fire success notifications but now we deleted it. Thanks

**Comment by callensm** [comment]
I would say alternative 1 would be better. Have the transaction sending functions return the signature and then calculate the explorer link/notification within there.

**Comment by Tristyn** [comment]
> I should return [res, txid] after we send transactions like we did on v1

How about you return `txid` and send notifications from each modal. We don't need [res, txid] because we can determine the type of response by looking at the error thrown

**Review by Tristyn — CHANGES_REQUESTED** [review]
return txid to send notifications

**Pull request closed without merging**
